name: Dockerfile Lint

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "Dockerfile"
      - "Dockerfile.*"
      - ".dockerignore"
  push:
    branches: [main, develop]
    paths:
      - "Dockerfile"
      - "Dockerfile.*"
      - ".dockerignore"

permissions:
  contents: read

jobs:
  hadolint:
    name: Dockerfile Lint (hadolint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
