name: Snyk Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Snyk to check for vulnerabilities
        if: env.SNYK_TOKEN != ''
        uses: snyk/actions/node@b98d498629f1c368650224d6d212bf7dfa89e4bf # 0.4.0
        with:
          args: --severity-threshold=high
