name: Spell Check

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spell Check (cspell)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
        with:
          config: cspell.json
          files: "**/*.{ts,md,json,yml,yaml}"
          incremental_files_only: true
          strict: false
